# Qdrant Vector Database Configuration
# Owner: VP of AI

version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: ytempire-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      # Uncomment for production with authentication
      # QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    networks:
      - ytempire-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_storage:
    driver: local

networks:
  ytempire-network:
    external: true
    name: ytempire_ytempire-network