version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ytempire_postgres
    environment:
      POSTGRES_USER: ytempire
      POSTGRES_PASSWORD: ytempire_secure_pwd_2024
      POSTGRES_DB: ytempire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ytempire_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ytempire"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: ytempire_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ytempire_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ytempire_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://ytempire:ytempire_secure_pwd_2024@postgres:5432/ytempire_db
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - ytempire_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ytempire_celery_worker
    environment:
      DATABASE_URL: postgresql+asyncpg://ytempire:ytempire_secure_pwd_2024@postgres:5432/ytempire_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./data:/app/data
    networks:
      - ytempire_network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: celery -A app.core.celery_app worker --loglevel=info

  # Celery Beat Scheduler
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ytempire_celery_beat
    environment:
      DATABASE_URL: postgresql+asyncpg://ytempire:ytempire_secure_pwd_2024@postgres:5432/ytempire_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
    networks:
      - ytempire_network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: celery -A app.core.celery_app beat --loglevel=info

  # Flower - Celery Monitoring
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ytempire_flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "5555:5555"
    networks:
      - ytempire_network
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped
    command: celery -A app.core.celery_app flower --port=5555

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ytempire_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ytempire_network
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3000

  # N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: ytempire_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ytempire_n8n_2024
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ytempire_network
    restart: unless-stopped

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: ytempire_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - ytempire_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: ytempire_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ytempire_grafana_2024
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - ytempire_network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  ytempire_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  prometheus_data:
  grafana_data: