# HashiCorp Vault Docker Compose
# Owner: Security Engineer #1

version: '3.9'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: ytempire_vault
    restart: unless-stopped
    
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
      
    ports:
      - "8200:8200"
      - "8201:8201"
      
    volumes:
      - ./vault-config.hcl:/vault/config/vault.hcl:ro
      - ./policies:/vault/policies:ro
      - ./scripts:/vault/scripts:ro
      - vault_data:/opt/vault/data
      - vault_logs:/vault/logs
      
    cap_add:
      - IPC_LOCK
      
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]
    
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    networks:
      - vault_network
  
  # Vault UI (optional, for development)
  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: ytempire_vault_ui
    restart: unless-stopped
    
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: USERPASS
      
    ports:
      - "8000:8000"
      
    depends_on:
      vault:
        condition: service_healthy
        
    networks:
      - vault_network

volumes:
  vault_data:
    driver: local
  vault_logs:
    driver: local

networks:
  vault_network:
    driver: bridge