"""Initial migration with String IDs

Revision ID: 653dd9b7e6c7
Revises: 
Create Date: 2025-08-11 10:07:41.057660+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "653dd9b7e6c7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_aggregations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("period_type", sa.String(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("operation_count", sa.Integer(), nullable=True),
        sa.Column("video_count", sa.Integer(), nullable=True),
        sa.Column("user_count", sa.Integer(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_aggregations_period_start"),
        "cost_aggregations",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_aggregations_service"),
        "cost_aggregations",
        ["service"],
        unique=False,
    )
    op.create_table(
        "cost_thresholds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("threshold_type", sa.String(), nullable=False),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("alert_email", sa.String(), nullable=True),
        sa.Column("alert_webhook", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("verification_token", sa.String(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_reset_token", sa.String(), nullable=True),
        sa.Column("password_reset_expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscription_tier", sa.String(), nullable=True),
        sa.Column("subscription_status", sa.String(), nullable=True),
        sa.Column("subscription_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channels_limit", sa.Integer(), nullable=True),
        sa.Column("videos_per_day_limit", sa.Integer(), nullable=True),
        sa.Column("monthly_budget_limit", sa.Float(), nullable=True),
        sa.Column("api_quota_remaining", sa.Integer(), nullable=True),
        sa.Column("api_quota_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_videos_generated", sa.Integer(), nullable=True),
        sa.Column("total_revenue_generated", sa.Float(), nullable=True),
        sa.Column("total_cost_incurred", sa.Float(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_password_reset_token"),
        "users",
        ["password_reset_token"],
        unique=True,
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(
        op.f("ix_users_verification_token"),
        "users",
        ["verification_token"],
        unique=True,
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("youtube_channel_id", sa.String(), nullable=True),
        sa.Column("youtube_channel_url", sa.String(), nullable=True),
        sa.Column("youtube_api_key", sa.String(), nullable=True),
        sa.Column("youtube_refresh_token", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("api_secret", sa.String(), nullable=True),
        sa.Column("target_audience", sa.String(), nullable=True),
        sa.Column("upload_schedule", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("posting_schedule", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("auto_generate", sa.Boolean(), nullable=True),
        sa.Column("auto_publish", sa.Boolean(), nullable=True),
        sa.Column("quality_threshold", sa.Float(), nullable=True),
        sa.Column("subscriber_count", sa.Integer(), nullable=True),
        sa.Column("total_views", sa.Integer(), nullable=True),
        sa.Column("total_videos", sa.Integer(), nullable=True),
        sa.Column("average_views", sa.Float(), nullable=True),
        sa.Column("is_monetized", sa.Boolean(), nullable=True),
        sa.Column("estimated_revenue", sa.Float(), nullable=True),
        sa.Column("rpm", sa.Float(), nullable=True),
        sa.Column("voice_id", sa.String(), nullable=True),
        sa.Column("style_preferences", sa.JSON(), nullable=True),
        sa.Column("content_guidelines", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_video_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_index(
        op.f("ix_channels_youtube_channel_id"),
        "channels",
        ["youtube_channel_id"],
        unique=True,
    )
    op.create_table(
        "cost_budgets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("budget_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("spent", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("videos_per_month", sa.Numeric(precision=10, scale=0), nullable=True),
        sa.Column(
            "api_calls_per_month", sa.Numeric(precision=10, scale=0), nullable=True
        ),
        sa.Column("storage_gb", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_table(
        "analytics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("period_type", sa.String(), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscriber_count", sa.Integer(), nullable=True),
        sa.Column("subscriber_growth", sa.Integer(), nullable=True),
        sa.Column("total_views", sa.Integer(), nullable=True),
        sa.Column("view_growth", sa.Integer(), nullable=True),
        sa.Column("videos_published", sa.Integer(), nullable=True),
        sa.Column("average_views_per_video", sa.Float(), nullable=True),
        sa.Column("average_watch_time", sa.Float(), nullable=True),
        sa.Column("average_engagement_rate", sa.Float(), nullable=True),
        sa.Column("estimated_revenue", sa.Float(), nullable=True),
        sa.Column("actual_revenue", sa.Float(), nullable=True),
        sa.Column("rpm", sa.Float(), nullable=True),
        sa.Column("cpm", sa.Float(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("cost_per_video", sa.Float(), nullable=True),
        sa.Column("roi", sa.Float(), nullable=True),
        sa.Column("profit_margin", sa.Float(), nullable=True),
        sa.Column("best_performing_video", sa.JSON(), nullable=True),
        sa.Column("worst_performing_video", sa.JSON(), nullable=True),
        sa.Column("trending_topics", sa.JSON(), nullable=True),
        sa.Column("audience_demographics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("youtube_video_id", sa.String(), nullable=True),
        sa.Column("youtube_url", sa.String(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("voice_script", sa.Text(), nullable=True),
        sa.Column("visual_prompts", sa.JSON(), nullable=True),
        sa.Column("video_file_path", sa.String(), nullable=True),
        sa.Column("audio_file_path", sa.String(), nullable=True),
        sa.Column("thumbnail_file_path", sa.String(), nullable=True),
        sa.Column("generation_status", sa.String(), nullable=True),
        sa.Column("generation_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_time_seconds", sa.Integer(), nullable=True),
        sa.Column("publish_status", sa.String(), nullable=True),
        sa.Column("scheduled_publish_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("trend_score", sa.Float(), nullable=True),
        sa.Column("engagement_prediction", sa.Float(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("dislike_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("share_count", sa.Integer(), nullable=True),
        sa.Column("watch_time_minutes", sa.Float(), nullable=True),
        sa.Column("is_monetized", sa.Boolean(), nullable=True),
        sa.Column("estimated_revenue", sa.Float(), nullable=True),
        sa.Column("actual_revenue", sa.Float(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("script_cost", sa.Float(), nullable=True),
        sa.Column("voice_cost", sa.Float(), nullable=True),
        sa.Column("video_cost", sa.Float(), nullable=True),
        sa.Column("thumbnail_cost", sa.Float(), nullable=True),
        sa.Column("script_model", sa.String(), nullable=True),
        sa.Column("voice_model", sa.String(), nullable=True),
        sa.Column("video_model", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("file_size_mb", sa.Float(), nullable=True),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("aspect_ratio", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_videos_youtube_video_id"), "videos", ["youtube_video_id"], unique=True
    )
    op.create_table(
        "costs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("service_type", sa.String(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("units", sa.Float(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("tokens_used", sa.JSON(), nullable=True),
        sa.Column("characters_used", sa.Float(), nullable=True),
        sa.Column("api_calls", sa.Float(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_costs_created_at"), "costs", ["created_at"], unique=False)
    op.create_index(op.f("ix_costs_operation"), "costs", ["operation"], unique=False)
    op.create_index(
        op.f("ix_costs_service_type"), "costs", ["service_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_costs_service_type"), table_name="costs")
    op.drop_index(op.f("ix_costs_operation"), table_name="costs")
    op.drop_index(op.f("ix_costs_created_at"), table_name="costs")
    op.drop_table("costs")
    op.drop_index(op.f("ix_videos_youtube_video_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_table("analytics")
    op.drop_table("subscriptions")
    op.drop_table("cost_budgets")
    op.drop_index(op.f("ix_channels_youtube_channel_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_users_verification_token"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_password_reset_token"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("cost_thresholds")
    op.drop_index(op.f("ix_cost_aggregations_service"), table_name="cost_aggregations")
    op.drop_index(
        op.f("ix_cost_aggregations_period_start"), table_name="cost_aggregations"
    )
    op.drop_table("cost_aggregations")
    # ### end Alembic commands ###
